### ISSUE TITLE
Add fats support for streaming runtime 

### ISSUE THREAD

**Issue by jldec** [projectriff/fats#214]
FATS coverage is required to release streaming runtime with riff ~~v0.5.0~~ 
Feb 6: bumped to v0.6.0.

**Comment by jldec** [comment]
Current status on this is that FATS streaming tests are [still disabled](https://github.com/projectriff/fats/blob/master/.github/workflows/run.sh#L83).

@sbawaska @scothis can you clarify whether this is in-scope for the v0.5.0 milestone?

**Comment by scothis** [comment]
We have streaming FATS tests in the system repo, but nowhere else. We should test the streaming runtime everywhere we test the core/knative runtimes.

It would be good to get this in for 0.5

**Comment by scothis** [comment]
See https://github.com/projectriff/system/pull/304 and https://github.com/projectriff/release/pull/138

**Comment by scothis** [comment]
@sbawaska @ojhughes any update here?

**Comment by ojhughes** [comment]
I have some WIP
