### ISSUE TITLE
Consider a go-based test harness

### ISSUE THREAD

**Issue by scothis** [projectriff/fats#250]
FATS is a pile a bash scripts. Bash is useful for quick and dirty scripts, but does not scale well as more people need to interact consume and author the system. Especially as bash is not a common language across the team, and no-one is particularly strong (or admits to being strong).

There are a few key aspects of FATS that I'd like to preserve:
- library of capabilities that are composed by the component under test to fit its specific needs
- platform/os agnostic (runs on Linux and Windows)
- extensible to add new tools, cluster, registries, workloads (functions, applications) and macros
- versioned so that consumers are not surprised by changes

Some things we can do better:
- explicit interfaces: many of the current contracts are loose a typed language can have typed interfaces
- extensibility: end-users should be able to extend any extensible element of the system as if it was first party (like adding a custom tool, or cluster)
- configurability: many components offer some configurability, but it's non-uniform (like tool versions). Other aspects should be configurable, but are not (like k8s version)
- local development: most tests will run in CI, but while developing and debugging, local support is crucial #249

**Comment by ojhughes** [comment]
[bazel test](https://docs.bazel.build/versions/2.0.0/test-encyclopedia.html) could be a good fit as there is good integration with k8s and support for running scripts

**Comment by scothis** [comment]
@ojhughes the idea was to have a test suite more members of the team can understand
