### ISSUE TITLE
localkube is not a valid minikube bootstrapper anymore

### ISSUE THREAD

**Issue by fbiville** [projectriff/fats#39]
New release has been done 3 days ago: https://github.com/kubernetes/minikube/releases/tag/v0.29.0
It includes the removal of localkube: https://github.com/kubernetes/minikube/pull/2911.

This currently blocks FATS on minikube: https://travis-ci.org/projectriff/fats/jobs/435507850#L508.

**Comment by fbiville** [comment]
I hardcoded minikube to `v0.28.2` for now.

**Comment by scothis** [comment]
We should restore tracking the latest Minikube releases once https://github.com/kubernetes/minikube/issues/2704 has been resolved. Until then we are blocked.

https://github.com/LiliC/travis-minikube/tree/lili/test-minikube29-k8s112 is a good resource to track.

**Comment by fbiville** [comment]
It seems https://github.com/LiliC/travis-minikube/tree/minikube-30-kube-1.12 is up and running with the latest version of minikube \o/

**Comment by trisberg** [comment]
This has been fixed by upgrading to minikube v0.30.0 and kubernetes 1.12.2 in feeaf28
