### ISSUE TITLE
Test riff on Windows

### ISSUE THREAD

**Issue by scothis** [projectriff/fats#46]
Travis CI now has Windows available as a runtime. It would be nice to test the Windows CLI binary.

cc @fbiville

**Comment by fbiville** [comment]
I will give it a try today

**Comment by fbiville** [comment]
For future references: https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by fbiville** [comment]
My fear is that kail might not be installable on Windows. Trying to confirm ASAP.

**Comment by fbiville** [comment]
I managed to install kail on a Windows machine by duplicating some instructions from the `Makefile` (for some reason, GNU Make does not seem to do anything when called).
However, `choco install kubernetes-cli` hangs forever in Travis CI, I have no idea why.

**Comment by fbiville** [comment]
Posted in Travis community support: https://travis-ci.community/t/choco-install-hangs-forever/307

**Comment by fbiville** [comment]
Here is a maintained list of blockers:

 - Travis worker is stuck with choco install when a build has secret envvars: [issue](https://travis-ci.community/t/choco-install-hangs-forever/307/6)
 - kail.exe won't recognize `/dev/stderr` and won't run: [issue](https://github.com/boz/kail/issues/23)
 - Minikube option `--vm-driver=none` is not supported on Windows
