### ISSUE TITLE
fix .travis.fats-trigger.sh

### ISSUE THREAD

**Issue by scothis** [projectriff/fats#50]
The .travis.fats-trigger.sh script stopped triggering fats. See https://travis-ci.org/projectriff/riff/jobs/449162152

**Comment by sbawaska** [comment]
enabling debug shows this error:
```
request='{
  "@type": "error"
  "error_type": "insufficient_access"
  "error_message": "operation requires create_request access to repository"
  "resource_type": "repository"
  "permission": "create_request"
  "repository": {
    "@type": "repository"
    "@href": "/repo/17557048"
    "@representation": "minimal"
    "id": 17557048
    "name": "fats"
    "slug": "projectriff/fats"
  }
}
```
@scothis Do you know if TRAVIS_API_TOKEN expires OR any other recent changes to it? I tried using TOKEN from my [profile page](https://travis-ci.com/account/preferences), but no joy.

**Comment by scothis** [comment]
Looks like the travis api token set in the projectriff/riff went bad. Replacing it with a current token allowed builds to trigger again.

**Comment by georgeharley** [comment]
@sbawaska FWIW it seems that the token on your Travis profile page is not what the API expects. Instead, it wants the token value to be the response from the `travis token` CLI command.
